import { PremiumFeature, isFeatureUnlocked } from './premiumRegistry';
export const ContentTier = { BASIC: 'basic', PREMIUM: 'premium' };
export const premiumContentIds = new Set([
  'listening_flight_delay_announcement',
  'listening_research_funding_lecture',
  'listening_conference_registration',
  'listening_visa_appointment_briefing',
  'listening_statistics_workshop_lecture',
  'listening_memory_neuroscience_lecture',
  'listening_corporate_merger_briefing',
  'listening_climate_policy_panel',
  'listening_sustainable_architecture_talk',
  'listening_cybersecurity_awareness_talk',
  'listening_tenancy_rights_briefing',
  'listening_space_exploration_lecture',
  'listening_corporate_relocation',
  'listening_housing_market_economics_lecture',
  'listening_global_supply_chain_lecture',
  'listening_ai_ethics_talk',
  'listening_behavioral_economics_talk',
  'listening_negotiation_skills_workshop',
  'listening_international_trade_law_briefing',
  'listening_quantum_computing_basics_talk',
  'writing_line_graph_internet_usage',
  'writing_pie_chart_household_spending',
  'writing_mixed_chart_renewable_investment',
  'writing_line_graph_life_expectancy',
  'writing_process_desalination_plant',
  'writing_map_airport_expansion',
  'writing_pie_chart_research_funding_sources',
  'writing_bar_chart_healthcare_spending',
  'writing_table_startup_funding_rounds',
  'writing_formal_planning_objection_letter',
  'writing_essay_task2_crime_prevention',
  'writing_essay_task2_media_influence',
  'writing_essay_task2_transport_investment',
  'writing_essay_task2_ai_regulation',
  'writing_essay_task2_immigration_economy',
  'writing_essay_task2_genetic_engineering',
  'writing_essay_task2_corporate_tax_avoidance',
  'writing_essay_task2_freedom_of_speech_limits',
  'writing_essay_task2_space_colonization_ethics',
  'writing_essay_task2_universal_basic_income',
  'speaking_part1_v4',
  'speaking_part1_v5',
  'speaking_part1_v16',
  'speaking_part1_v17',
  'speaking_part1_v18',
  'speaking_part1_v19',
  'speaking_part1_v20',
  'speaking_part2_v3',
  'speaking_part2_v4',
  'speaking_part2_v16',
  'speaking_part2_v17',
  'speaking_part2_v18',
  'speaking_part2_v19',
  'speaking_part2_v20',
  'speaking_part3_v3',
  'speaking_part3_v4',
  'speaking_part3_v17',
  'speaking_part3_v18',
  'speaking_part3_v19',
  'speaking_part3_v20',
]);
export function tierOf(contentId) { return premiumContentIds.has(contentId) ? ContentTier.PREMIUM : ContentTier.BASIC; }
export function isPremiumContent(contentId) { return tierOf(contentId) === ContentTier.PREMIUM; }
export function isContentAccessible(contentId, entitlements) {
  if (tierOf(contentId) === ContentTier.BASIC) return true;
  return isFeatureUnlocked(PremiumFeature.PREMIUM_CONTENT_LIBRARY, entitlements);
}
