/**
 * Customer IDs are generated by the app (see premiumRegistry.js) as
 * PRP-<8 base36>-<6 base36>, upper-case. This file is imported by BOTH the
 * browser bundle and the serverless functions, so the two can never
 * disagree about what a valid ID looks like. It has no imports on purpose.
 */
export const CUSTOMER_ID_PATTERN = /^PRP-[A-Z0-9]{8}-[A-Z0-9]{6}$/;

/** Trims and upper-cases (a 1:1 mapping, so it cannot make two different
 * IDs collide), then validates. Returns the canonical ID or null. */
export function normalizeCustomerId(raw) {
  if (typeof raw !== 'string') return null;
  const id = raw.trim().toUpperCase();
  return CUSTOMER_ID_PATTERN.test(id) ? id : null;
}
